RobotArm_NoCollision:
  # Publish all joint states -----------------------------------
  # joint_state_controller:
  #   type: joint_state_controller/JointStateController
  #   publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  kata_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  hiji_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: dxl430_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  tekubi_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: dxl430_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}